# Generated by Django 4.0.3 on 2022-03-15 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseManagement', '0002_application_renter_id_application_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='identity_proof_id',
            new_name='identity_proof',
        ),
        migrations.RemoveField(
            model_name='application',
            name='renter_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='unit_lease',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='unit_lease',
            name='unit_id',
        ),
    ]
