# Generated by Django 4.0.3 on 2022-03-16 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseManagement', '0003_rename_identity_proof_id_renter_identity_proof_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
