# Generated by Django 4.0.3 on 2022-03-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseManagement', '0002_application_renter_id_application_staff_id_and_more'),
        ('staffManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_payment_log',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffManagement.staff'),
        ),
        migrations.AddField(
            model_name='rent_payment_log',
            name='unit_lease_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseManagement.unit_lease'),
        ),
        migrations.AddField(
            model_name='service_request',
            name='Service_Category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffManagement.service_category'),
        ),
        migrations.AddField(
            model_name='service_request',
            name='unit_lease_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseManagement.unit_lease'),
        ),
    ]
