# Generated by Django 4.0.3 on 2022-03-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseManagement', '0005_application_renter_application_unit_and_more'),
        ('staffManagement', '0003_remove_rent_payment_log_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_payment_log',
            name='unit_lease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseManagement.unit_lease'),
        ),
        migrations.AddField(
            model_name='service_request',
            name='Service_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffManagement.service_category'),
        ),
        migrations.AddField(
            model_name='service_request',
            name='unit_lease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseManagement.unit_lease'),
        ),
    ]
