# Generated by Django 4.0.3 on 2022-03-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffManagement', '0004_rent_payment_log_unit_lease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_payment_log',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffManagement.staff'),
        ),
        migrations.AddField(
            model_name='service_request',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffManagement.staff'),
        ),
    ]
