# Generated by Django 4.0.3 on 2022-03-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffManagement', '0006_staff_app_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent_payment_log',
            name='unit_lease',
        ),
        migrations.RemoveField(
            model_name='service_request',
            name='Service_Category',
        ),
        migrations.RemoveField(
            model_name='service_request',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='service_request',
            name='unit_lease',
        ),
        migrations.DeleteModel(
            name='Staff_APP_Join',
        ),
    ]
