# Generated by Django 4.0.3 on 2022-03-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
