# Generated by Django 4.0.3 on 2022-03-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitManagement', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='community_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='leasing_info_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type_id',
        ),
    ]
