# Generated by Django 4.0.3 on 2022-03-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitManagement', '0004_remove_community_address_id_remove_unit_address_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unitManagement.address'),
        ),
        migrations.AddField(
            model_name='unit',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unitManagement.address'),
        ),
        migrations.AddField(
            model_name='unit',
            name='community_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unitManagement.community'),
        ),
        migrations.AddField(
            model_name='unit',
            name='leasing_info_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unitManagement.leasing_info'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unitManagement.unittype'),
        ),
    ]
