# Generated by Django 4.0.3 on 2022-03-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitManagement', '0005_community_address_id_unit_address_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unittype',
            old_name='unit_Type',
            new_name='unit_type',
        ),
    ]
